- name: Deploy with gh-pages
  run: |
    git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
    npm run deploy
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}